### ISSUE TITLE
Auto-generate the client

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-client-python#2]
Use Kill Bill's [swagger-codegen](https://github.com/killbill/killbill-swagger-coden) to generate all missing API calls.

This is an experiment to compare the pros and cons of auto-generating clients. See [this thread](https://groups.google.com/forum/#!topic/killbilling-users/ciKHBH_qL1c) for more background.

For testing, come up with a small suite similar to the [Ruby one](https://github.com/killbill/killbill-client-ruby/blob/work-for-release-0.19.x/spec/killbill_client/remote/model_spec.rb) to test the principal calls (such as create tenant, create/get account, create/get subscription, trigger invoice generation, create/get payment). No need to go for 100% coverage.

Notes:

* To be done on the `work-for-release-0.19.x` branch only
* Use `work-for-release-0.19.x-doc` in Kill Bill as the Swagger reference branch
* We need to support Python 2.5, 2.7 and 3.6
* Make sure the profiling framework is still supported (see https://github.com/killbill/killbill-client-python/commit/f634548bb818dc404b0d207459287fc54f12eb24 and https://github.com/killbill/killbill/wiki/Kill-Bill-Profiling)
* Make sure the HTTP backend is still configurable (see https://github.com/killbill/killbill-client-python/commit/5f70864270d2f0f946c766a8f4046742ec952861)
* ~According to the [thread](https://groups.google.com/forum/#!topic/killbilling-users/ciKHBH_qL1c), there are some issues with the Swagger annotations. Instead of fixing the generated `.yaml` by hand, try to fix the annotations instead~ This should mostly be taken care of in `work-for-release-0.19.x-doc`
* Update the README with instructions on how to regenerate the client
* Documentation (snippets) to update

**Comment by sbrossie** [comment]
In terms of testing, the proposal is to write a few small scenarii that would provide a good coverage to have confidence that generated code works as expected -- without going into the trouble of testing every single api. The test scenarii could live inside the python client, and would be an integration test against a running Kill Bill server instance.

**Scenario 1 : Basic flow **

1. Create tenant
2. Upload XML catalog/Fetch XML catalog -- at least one simple RECURRING plan
3. Create account
4. Add a payment method (could use default 'EXTERNAL')
5. Tag account as AUTO_INVOICING_OFF
6. Create a subscription against plan -> No invoice generated because of tag
7. Remove Tag => Invoice should be generated, and payment as well
8. Create a dryRun invoice (next targetDate)
9. Modify Plan (more expensive) associated to subscription immediately -> new invoice, payment
10. Create Refund with item adjustment for last payment invoice and verify $0 account balance
11. Cancel subscription immediatelty
12. Retrieve subscription -- and verify state

**Scenario 2 : Paginations/Search **

1. Create a few accounts (~10)
2. Add payment methods (could use default 'EXTERNAL')
3. Create some external charges -> invoices, payments
4. Use pagination apis to list accounts, payment, invoices
5. Use search apis to search for a given account, payment, ...

**Comment by sbrossie** [comment]
In terms of testing, the proposal is to write a few small scenarii that would provide a good coverage to have confidence that generated code works as expected -- without going into the trouble of testing every single api. The test scenarii could live inside the python client, and would be an integration test against a running Kill Bill server instance.

**Scenario 1 : Basic flow**

1. Create tenant
2. Upload XML catalog/Fetch XML catalog -- at least one simple RECURRING plan
3. Create account
4. Add a payment method (could use default 'EXTERNAL')
5. Tag account as AUTO_INVOICING_OFF
6. Create a subscription against plan -> No invoice generated because of tag
7. Remove Tag => Invoice should be generated, and payment as well
8. Create a dryRun invoice (next targetDate)
9. Modify Plan (more expensive) associated to subscription immediately -> new invoice, payment
10. Create Refund with item adjustment for last payment invoice and verify $0 account balance
11. Cancel subscription immediatelty
12. Retrieve subscription -- and verify state

**Scenario 2 : Paginations/Search**

1. Create a few accounts (~10)
2. Add payment methods (could use default 'EXTERNAL')
3. Create some external charges -> invoices, payments
4. Use pagination apis to list accounts, payment, invoices
5. Use search apis to search for a given account, payment, ...
